Write-Host "Phase 3 services:"
Write-Host "1. dotnet run --project services/job-catalog-service/src/FJob.JobCatalogService --launch-profile http"
Write-Host "2. dotnet run --project services/crawl-orchestration-service/src/FJob.CrawlOrchestrationService --launch-profile http"
Write-Host "3. dotnet run --project services/job-search-service/src/FJob.JobSearchService --launch-profile http"
Write-Host "4. dotnet run --project services/api-gateway/src/FJob.ApiGateway --launch-profile http"
Write-Host "5. dotnet run --project services/frontend-web/src/FJob.FrontendWeb --launch-profile http"
Write-Host ""
Write-Host "Then open:"
Write-Host "http://localhost:5105"
Write-Host ""
Write-Host "Seed a crawl first if needed:"
Write-Host "Invoke-RestMethod -Method Post -Uri http://localhost:5102/api/crawl-requests -ContentType 'application/json' -Body '{\"source\":\"TopCV\",\"keyword\":\"python intern\",\"triggeredBy\":\"admin\"}'"
