Write-Host "Start MySQL first:"
Write-Host "Preferred local option: .\\scripts\\start-local-mysql.ps1"
Write-Host "Alternative Docker option: docker compose up -d mysql"
Write-Host ""
Write-Host "Then run services in this order:"
Write-Host "1. dotnet run --project services/identity-access-service/src/FJob.IdentityAccessService --launch-profile http"
Write-Host "2. dotnet run --project services/job-catalog-service/src/FJob.JobCatalogService --launch-profile http"
Write-Host "3. dotnet run --project services/crawl-orchestration-service/src/FJob.CrawlOrchestrationService --launch-profile http"
Write-Host "4. dotnet run --project services/job-search-service/src/FJob.JobSearchService --launch-profile http"
Write-Host "5. dotnet run --project services/api-gateway/src/FJob.ApiGateway --launch-profile http"
Write-Host "6. dotnet run --project services/frontend-web/src/FJob.FrontendWeb --launch-profile http"
Write-Host "7. dotnet run --project services/admin-operations-service/src/FJob.AdminOperationsService --launch-profile http"
Write-Host ""
Write-Host "Suggested smoke checks:"
Write-Host "- GET http://localhost:5104/metrics"
Write-Host "- GET http://localhost:5101/metrics"
Write-Host "- GET http://localhost:5102/metrics"
Write-Host "- GET http://localhost:5103/metrics"
Write-Host "- GET http://localhost:5100/metrics"
Write-Host "- GET http://localhost:5105/metrics"
Write-Host "- GET http://localhost:5105/ready"
Write-Host "- GET http://localhost:5106/metrics (requires admin token)"
Write-Host ""
Write-Host "Rate limiting checks:"
Write-Host "- Login endpoint: POST http://localhost:5104/api/auth/login"
Write-Host "- Search endpoint: POST http://localhost:5100/api/jobs/search"
Write-Host ""
Write-Host "Admin dashboard:"
Write-Host "http://localhost:5106"
Write-Host ""
Write-Host "React frontend:"
Write-Host "http://localhost:5105"
Write-Host ""
Write-Host "Local seed accounts:"
Write-Host "- operator: admin.operator / Operator@123"
Write-Host "- readonly: admin.viewer / Viewer@123"
