Write-Host "Start MySQL first:"
Write-Host "Preferred local option: .\\scripts\\start-local-mysql.ps1"
Write-Host "Alternative Docker option: docker compose up -d mysql"
Write-Host ""
Write-Host "Then run services:"
Write-Host "1. dotnet run --project services/identity-access-service/src/FJob.IdentityAccessService --launch-profile http"
Write-Host "2. dotnet run --project services/job-catalog-service/src/FJob.JobCatalogService --launch-profile http"
Write-Host "3. dotnet run --project services/crawl-orchestration-service/src/FJob.CrawlOrchestrationService --launch-profile http"
Write-Host "4. dotnet run --project services/admin-operations-service/src/FJob.AdminOperationsService --launch-profile http"
Write-Host ""
Write-Host "Open admin dashboard:"
Write-Host "http://localhost:5106"
Write-Host ""
Write-Host "Local seed accounts:"
Write-Host "- operator: admin.operator / Operator@123"
Write-Host "- readonly: admin.viewer / Viewer@123"
