Write-Host "Phase 4 services:"
Write-Host "1. dotnet run --project services/job-catalog-service/src/FJob.JobCatalogService --launch-profile http"
Write-Host "2. dotnet run --project services/crawl-orchestration-service/src/FJob.CrawlOrchestrationService --launch-profile http"
Write-Host "3. dotnet run --project services/admin-operations-service/src/FJob.AdminOperationsService --launch-profile http"
Write-Host ""
Write-Host "Then open:"
Write-Host "http://localhost:5106"
Write-Host ""
Write-Host "Example manual trigger via API:"
Write-Host "Invoke-RestMethod -Method Post -Uri http://localhost:5106/api/admin/crawl-requests -ContentType 'application/json' -Body '{\"source\":\"TopCV\",\"keyword\":\"python intern\",\"triggeredBy\":\"admin-ui\"}'"
