Write-Host "Phase 2 services:"
Write-Host "1. dotnet run --project services/job-catalog-service/src/FJob.JobCatalogService --launch-profile http"
Write-Host "2. dotnet run --project services/crawl-orchestration-service/src/FJob.CrawlOrchestrationService --launch-profile http"
Write-Host "3. dotnet run --project services/job-search-service/src/FJob.JobSearchService --launch-profile http"
Write-Host "4. dotnet run --project services/api-gateway/src/FJob.ApiGateway --launch-profile http"
Write-Host ""
Write-Host "Trigger crawl:"
Write-Host "Invoke-RestMethod -Method Post -Uri http://localhost:5102/api/crawl-requests -ContentType 'application/json' -Body '{\"source\":\"TopCV\",\"keyword\":\"python intern\",\"triggeredBy\":\"admin\"}'"
Write-Host ""
Write-Host "Search through gateway:"
Write-Host "Invoke-RestMethod -Method Post -Uri http://localhost:5100/api/jobs/search -ContentType 'application/json' -Body '{\"keyword\":\"python intern\",\"page\":1,\"pageSize\":10,\"sortBy\":\"relevance\"}'"
